Update concept-profile-engine-cpp.md grammar
MicrosoftDocs/Azure-RMSDocs pull request #1414
Opened 2021-11-18 14:35 UTC by cdietschrun

#1413 simple grammar tweak

2021-11-18 14:35 UTC, PRMerger15 commented
@cdietschrun : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2021-11-18 14:39 UTC, PRMerger4 commented
@cdietschrun : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2021-11-18 14:43 UTC, PRMerger17 commented
@cdietschrun : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2021-11-18 14:59 UTC, PRMerger5 commented
@cdietschrun : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2021-11-18 15:07 UTC, PRMerger-2 commented
@cdietschrun : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2021-11-18 15:11 UTC, PRMerger18 commented
@cdietschrun : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2021-11-18 16:55 UTC, ktoliver commented
#label:"aq-pr-triaged"

2021-12-09 17:10 UTC, ktoliver commented
@tommoser Could you review the proposed code changes in **mip/develop/concept-delegation.md**?

All other changes look good to me. . .

Thanks.

2021-12-12 12:42 UTC, batamig commented
Hi @cdietschrun - thanks again for contributing to docs! 

I'm tagging the focal points on the team and have closed the related issues so as to consolidate any conversation.
I also agree that the grammar fixes look right, but we need approval before merging the code changes.

@tommoser  and @msmbaldwin, can you take a look?

2021-12-13 18:31 UTC, tommoser commented on mip/develop/concept-delegation.md
> +This sample demonstrates how to perform **delegated publishing**.
I think these are mixed up. The example headers were switched and said consumption for publishing and vice versa. This looks like you updated the sample code and then reversed the headers. We can either switch the headers only or leave the headers and take the sample code updates.

2021-12-13 18:32 UTC, tommoser requested changes
Thanks for the PR and feedback! It looks good other than that we need to clarify the change around the delegation scenarios and the consumption/publishing examples.

2022-01-04 09:13 UTC, batamig commented
Hi @tommoser - thanks for the feedback!
@cdietschrun, can you fix the confusion in the example headers before we merge this PR?
@tommoser, once that item is fixed, if there are other changes required, let's take offline into the backlog to update as needed.

2022-02-17 13:53 UTC, closed without merging